# PersistentVolume - 持久卷
# 作用：定义一块存储空间，供Pod使用
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv # PV的名称(全局唯一)
spec:
  capacity:
    storage: 5Gi # 存储容量
  accessModes:
    - ReadWriteOnce # 单节点读写
  hostPath:
    path: "/mnt/c/Code/social-media-hub/k8s-data/redis" # 本地存储路径
    type: DirectoryOrCreate