apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: social-media-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: social-media-hub-auth:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        hostPath:
          path: /mnt/c/Code/social-media-hub/config
          type: DirectoryOrCreate
