apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader
  namespace: social-media-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downloader
  template:
    metadata:
      labels:
        app: downloader
    spec:
      containers:
      - name: downloader
        image: social-media-hub-downloader:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        volumeMounts:
        - name: videos
          mountPath: /app/videos
        - name: config
          mountPath: /app/config
      volumes:
      - name: videos
        hostPath:
          path: /mnt/c/Code/social-media-hub/videos
          type: DirectoryOrCreate
      - name: config
        hostPath:
          path: /mnt/c/Code/social-media-hub/config
          type: DirectoryOrCreate
