{{- if .Values.biliupUploader.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biliup-uploader
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.biliupUploader.replicas }}
  selector:
    matchLabels:
      app: biliup-uploader
  template:
    metadata:
      labels:
        app: biliup-uploader
    spec:
      containers:
      - name: biliup-uploader
        image: {{ .Values.global.imageRegistry }}{{ .Values.biliupUploader.image.repository }}:{{ .Values.biliupUploader.image.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        env:
        - name: REDIS_URL
          value: {{ .Values.global.redis.url | quote }}
        volumeMounts:
        - name: videos
          mountPath: /app/videos
        - name: config
          mountPath: /app/config
        - name: chrome-profile
          mountPath: /app/chrome_profile
      volumes:
      - name: videos
        hostPath:
          path: {{ .Values.volumes.videos.hostPath }}
          type: DirectoryOrCreate
      - name: config
        hostPath:
          path: {{ .Values.volumes.config.hostPath }}
          type: DirectoryOrCreate
      - name: chrome-profile
        hostPath:
          path: {{ .Values.volumes.chromeProfile.hostPath }}
          type: DirectoryOrCreate
{{- end }}
