{{- if .Values.merger.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merger
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.merger.replicas }}
  selector:
    matchLabels:
      app: merger
  template:
    metadata:
      labels:
        app: merger
    spec:
      containers:
      - name: merger
        image: {{ .Values.global.imageRegistry }}{{ .Values.merger.image.repository }}:{{ .Values.merger.image.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        env:
        - name: REDIS_URL
          value: {{ .Values.global.redis.url | quote }}
        volumeMounts:
        - name: videos
          mountPath: /app/videos
      volumes:
      - name: videos
        hostPath:
          path: {{ .Values.volumes.videos.hostPath }}
          type: DirectoryOrCreate
{{- end }}
