{{- if .Values.scanner.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.scanner.replicas }}
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
      - name: scanner
        image: {{ .Values.global.imageRegistry }}{{ .Values.scanner.image.repository }}:{{ .Values.scanner.image.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        env:
        - name: REDIS_URL
          value: {{ .Values.global.redis.url | quote }}
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        hostPath:
          path: {{ .Values.volumes.config.hostPath }}
          type: DirectoryOrCreate
{{- end }}
