{{- if .Values.uploader.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.uploader.replicas }}
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      containers:
      - name: uploader
        image: {{ .Values.global.imageRegistry }}{{ .Values.uploader.image.repository }}:{{ .Values.uploader.image.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        env:
        - name: REDIS_URL
          value: {{ .Values.global.redis.url | quote }}
        volumeMounts:
        - name: videos
          mountPath: /app/videos
        - name: config
          mountPath: /app/config
      volumes:
      - name: videos
        hostPath:
          path: {{ .Values.volumes.videos.hostPath }}
          type: DirectoryOrCreate
      - name: config
        hostPath:
          path: {{ .Values.volumes.config.hostPath }}
          type: DirectoryOrCreate
{{- end }}
