apiVersion: apps/v1
kind: Deployment
metadata:
  name: merger
  namespace: social-media-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merger
  template:
    metadata:
      labels:
        app: merger
    spec:
      imagePullSecrets:
      - name: swr-secret
      containers:
      - name: merger
        image: swr.ap-southeast-2.myhuaweicloud.com/smh/merger:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
