apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner
  namespace: social-media-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      imagePullSecrets:
      - name: swr-secret
      containers:
      - name: scanner
        image: swr.ap-southeast-2.myhuaweicloud.com/smh/scanner:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: sessions-volume
          mountPath: /app/temp
      volumes:
      - name: config-volume
        configMap:
          name: accounts-config
      - name: sessions-volume
        secret:
          secretName: ins-sessions
