
apiVersion: apps/v1
kind: Deployment
metadata:
  name: standardizer
  namespace: social-media-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standardizer
  template:
    metadata:
      labels:
        app: standardizer
    spec:
      imagePullSecrets:
      - name: swr-secret
      containers:
      - name: standardizer
        image: swr.ap-southeast-2.myhuaweicloud.com/smh/standardizer:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
