apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader
  namespace: social-media-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      imagePullSecrets:
      - name: swr-secret
      containers:
      - name: uploader
        image: swr.ap-southeast-2.myhuaweicloud.com/smh/uploader:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
