apiVersion: apps/v1
kind: Deployment
metadata:
  name: standardizer
  namespace: social-media-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standardizer
  template:
    metadata:
      labels:
        app: standardizer
    spec:
      containers:
      - name: standardizer
        image: social-media-hub-standardizer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        volumeMounts:
        - name: videos
          mountPath: /app/videos
      volumes:
      - name: videos
        hostPath:
          path: /mnt/c/Code/social-media-hub/videos
          type: DirectoryOrCreate
